os: Visual Studio 2015 RC
version: "{build}"

configuration:
  - Debug
  - Release

install:
  ps: |
      $kspLibs = "Assembly-CSharp.dll", "Assembly-CSharp-firstpass.dll", "UnityEngine.dll"
      $kspLibsUrl = "http://build.apokee.com/dependencies/ksp/1.0.2"
      $kspLibsDir = "$env:APPVEYOR_BUILD_FOLDER/Library/KSP"

      New-Item $kspLibsDir -Type Directory -Force | Out-Null

      foreach ($kspLib in $kspLibs)
      {
        Start-FileDownload "$kspLibsUrl/$kspLib" -FileName "$kspLibsDir/$kspLib"
      }

before_build:
  ps: |
      $env:BUILD_VERSION = (cat VERSION)

build_script:
  ps: |
      ./build -configuration="$env:CONFIGURATION"

test: off

artifacts:
  - path: 'Output\Package\$(configuration)\*.zip'
    name: ZipPackage

deploy:
  - provider: GitHub
    release: v$(BUILD_VERSION)
    auth_token:
      secure: EmsGaC6JRUeanKOhuSCl3ka+kK0czrAG7LHBaYONuUWfV/rIARRFkwoSKZiZHWTe
    artifact: ZipPackage
    draft: true
    prerelease: false
    on:
      branch: master
      configuration: Release
      appveyor_repo_tag: true
